#ifndef SOF_ERROR_CODES_H
#define SOF_ERROR_CODES_H
#   define ERR_UNKNOW 0
#   define ERR_SOURCE_READ_ERROR 2
#   define ERR_EMPTY_FILE 3
#   define ERR_FILE_READING_ERROR 4
#   define ERR_IDENTIFIERS_ALLOCATION 5
#   define ERR_IDENTIFIER_ALLOCATION 6
#   define ERR_IDENTIFIER_IS_NOT_A_NUMBER 7
#   define ERR_IDENTIFIER_IS_NOT_A_VALID_NUMBER 8
#   define ERR_UNKNOW_OPERATOR 9
#   define ERR_UNKNOW_PLAT 10
#   define ERR_UNKNOW_OPERATION 11
#   define ERR_UNKNOW_IDENTIFIER 12
#   define ERR_TOKEN_PRE_TYPE_DEPENDENCIES_NOT_SATISFIED 13
#   define ERR_UNKNOW_TYPE_DEPENDENCY 14
#   define ERR_TOKEN_PRE_OPERATION_DEPENDENCIES_NOT_SATISFIED 14
#   define ERR_UNKNOW_OPERATION_DEPENDENCY 15
#endif // SOF_ERROR_CODES_H