#ifndef CORTH_ERROR_CODES_H
#define CORTH_ERROR_CODES_H
#   define ERR_SOURCE_READ_ERROR 1
#   define ERR_EMPTY_FILE 2
#   define ERR_FILE_READING_ERROR 3
#   define ERR_IDENTIFIERS_ALLOCATION 4
#   define ERR_IDENTIFIER_ALLOCATION 5
#endif // CORTH_ERROR_CODES_H